In [ ]:
import cv2
import numpy as np
import glob
from cameraCalibration import *

import importlib.util


module_name = "wrapper"  # can be anything
file_path = r"C:\Users\tad1i\projects\SIGMAxPortal301-Team2\src\wrapper.py"

spec = importlib.util.spec_from_file_location(module_name, file_path)
src = importlib.util.module_from_spec(spec)
spec.loader.exec_module(src)






In [29]:
imagesPath = "./chessboard pictures"
area = 4
calibrate_camera(imagesPath, area)


videoPath = r"C:\Users\tad1i\projects\SIGMAxPortal301-Team2\T1\TAD\chessboard pictures\video.mp4"
extract_frames(videoPath, imagesPath, 1)


Camera matrix:
 [[925.58276326   0.         611.31011179]
 [  0.         922.79772745 485.46757544]
 [  0.           0.           1.        ]]
Distortion coefficients:
 [[ 0.07650851 -0.12151219  0.00055373 -0.00617119 -0.09118735]]
Total reprojection error: 0.1422222454090928
Original FPS: 30.0, Duration: 231.70s, Total frames: 6951
Saved 232 frames to './chessboard pictures'
